# Generated by Django 4.2.4 on 2023-09-11 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SliderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('silder_image', models.ImageField(upload_to='static/uploads')),
                ('silde_titel', models.CharField(max_length=50)),
                ('slide_btn', models.CharField(max_length=50)),
                ('slider_discription', models.CharField(max_length=100)),
            ],
        ),
    ]
