# Generated by Django 4.2.4 on 2023-09-11 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider1Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slider_image', models.ImageField(upload_to='static/uploads')),
                ('slider_titel', models.CharField(max_length=50)),
                ('slider_btn', models.CharField(max_length=50)),
                ('slider_description', models.CharField(max_length=100)),
                ('slider_link', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='SliderModel',
        ),
    ]
