# Generated by Django 4.2.5 on 2023-09-12 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_brandmodel_categorymodel_productmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productmodel',
            old_name='category_color',
            new_name='product_color',
        ),
        migrations.AddField(
            model_name='productmodel',
            name='product_img',
            field=models.ImageField(default='', null=True, upload_to='static/uploads'),
        ),
        migrations.AlterField(
            model_name='categorymodel',
            name='category_logo',
            field=models.ImageField(upload_to='static/logo'),
        ),
    ]
