# Generated by Django 4.2.5 on 2023-09-13 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_usermodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhychooseusModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whychooseus_logo', models.FileField(upload_to='static/logo')),
                ('whychooseus_titel', models.TextField(max_length=100)),
                ('whychooseus_dis', models.TextField()),
            ],
        ),
    ]
