# Generated by Django 4.2.5 on 2023-09-14 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0007_upcommingmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='upcommingmodel',
            name='upcomming_name',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
