# Generated by Django 4.2.5 on 2023-09-14 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0008_upcommingmodel_upcomming_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upcommingmodel',
            name='upcomming_image',
            field=models.ImageField(upload_to='static/uploads'),
        ),
    ]
